apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-from-git
  namespace: vm-import
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: ubuntu-from-git
        test-label: works
    spec:
      domain:
        cpu:
          cores: 2
        resources:
          limits:
            memory: 3Gi
          requests:
            memory: 3Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          dataVolume:
            name: ubuntu-rootdisk
